### ISSUE TITLE
Zahtevi zadatka se ne poklapaju

### ISSUE THREAD

**Issue by dsheedes** [programiranje2fon/kolokvijum2zadatak2#1]
Zadatak zahteva da se naprave atributi **sat** i **minut**, a GUI deo sadrži format dan/mesec/godina.
Testovi takođe provatavaju da li postoji atribut _GregorianCalendar vreme_, a ne sat i minut.

> Napraviti javnu klasu Polazak u paketu autobuska_stanica koja ima:
> .
> .
> .
> •Privatne atribute sat i minut koji predstavljaju sat i minut u danu polaska.
> .
> .
> .

**Comment by bojantomic** [comment]
Hvala na ispravci, tekst zadatka je ispravljen u skladu sa resenjem.
